repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        language: system
        types_or: [javascript, jsx, ts, tsx]
        entry: "yarn lint"
  - repo: local
    hooks:
      - id: format
        name: format
        language: system
        types_or: [javascript, jsx, ts, tsx]
        entry: "yarn format"
  - repo: local
    hooks:
      - id: typecheck
        name: typecheck
        language: system
        types_or: [ts, tsx]
        entry: "yarn typecheck"

